version: "3"

services:
  mongo:
    image: mongo:6
    container_name: my_mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    volumes:
      - mongo_data:/data/db

  server:
    build: ./server
    container_name: my_server
    restart: unless-stopped
    ports:
      - "4000:4000"      # Mapea el puerto 4000 interno al 4000 del host
    depends_on:
      - mongo
    env_file:
      - .env
    volumes:
      - ./server/src/uploads:/usr/src/app/src/uploads
      # (opcional) para que puedas ver las imágenes subidas en tu máquina

  client:
    build: ./client
    container_name: my_client
    restart: unless-stopped
    ports:
      - "3000:80"        # Mapea el 80 interno (Nginx) al 3000 del host
    depends_on:
      - server

volumes:
  mongo_data:
